baseURL = 'https://zaixrx.github.io/'
locale = 'en-us'
title = 'zaixrx blog'
theme = "nojs"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2
